### PR TITLE
Allow multitask creation

### PR DESCRIPTION
**Pull request by mitermayer**
This will allow creating of multi task files.

will solve issue:
https://github.com/gyllstromk/grunt-bowerful/issues/7

i also merged all my commits from my previous pull:

https://github.com/gyllstromk/grunt-bowerful/pull/11

that pull solves issues:

https://github.com/gyllstromk/grunt-bowerful/issues/6
https://github.com/gyllstromk/grunt-bowerful/issues/5

### CODE REVIEW

**Comment by mitermayer** [comment]
@gyllstromk  just finished testing this updates now, it looks all good to merge from my tests.  I am thinking about including some tests on this repo on the future to automate the testing procedures and also include them in travis so that they can be automatically run on every commit. what you reckon ? 

I really like this project and i hope to be able to contribute to it :)

**Comment by mitermayer** [comment]
updated customTarget to allow it to work with files extensions.

```
/**
  customtarget (optional) -> file targets can be manually specified. 

  string - fullpath string without any extenstion, this will be added automaticly.

  key/value pairs. - fullpath string with extensions, extensions can be overwritten. 
  eg: Changing ext to something else, example '.less' or '.scss' 
 */
customtarget: { 
   // this will generate jquery.js and jquery.css files if they exist on package
   jquery: 'web/js/vendor/jquery', 
   // note that you can overwrite the filename and extension to anything else.
   otherlib: {
       js: 'path/to/destination.js',
       css: 'path/to/destination.scss'
   }
},
```

**Comment by mitermayer** [comment]
@gyllstromk  if you want i can squash all my commits into '1' so this way don't pollute too much the history. Please let me know what you think and what would you want.

**Comment by mitermayer** [comment]
@gyllstromk added pull 14 with a single meaninful comment https://github.com/gyllstromk/grunt-bowerful/pull/14

**Comment by gyllstromk** [comment]
Thanks for the great work! It is now merged.

**Pull request merged**
